### ISSUE TITLE
Thanks man!

### ISSUE THREAD

**Issue by tkbstudios** [Broesmeli65/reddit_wallpaper_downloader#1]
Thank you for this great script hope you continue making great things 😊

**Comment by Broesmeli65** [comment]
Hey Dude, thanks i appreciate that u like my first real python code! I just saw that there is a problem if the post contains 2 or more images. I will try my best to fix this issue afaik.

**Comment by Broesmeli65** [comment]
Just wanted to let you know that i fixed the issue and uploaded the new code ;)

**Comment by tkbstudios** [comment]
No issues with the code for me currently but thanks for that great code!👍
